name = "r2-image-host"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
R2_PUBLIC_DOMAIN = "https://image.20250530.space"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "INDEXES_KV"
id = "bcb414d8957047c6afce7434145285f5"
preview_id = "bcb414d8957047c6afce7434145285f5"

# R2 存储桶绑定
[[r2_buckets]]
binding = "bucket-binding"
bucket_name = "image-sharer"


[site]
bucket = "src/static"

